<?php
return [
    ['city' => 'Phnom Penh', 'province' => 'Phnom Penh'],
    ['city' => 'Siem Reap', 'province' => 'Siem Reap'],
    ['city' => 'Sihanoukville', 'province' => 'Preah Sihanouk'],
    ['city' => 'Battambang', 'province' => 'Battambang'],
    ['city' => 'Kampot', 'province' => 'Kampot'],
    ['city' => 'Kep', 'province' => 'Kep'],
    ['city' => 'Kampong Cham', 'province' => 'Kampong Cham'],
    ['city' => 'Koh Kong', 'province' => 'Koh Kong'],
    ['city' => 'Kratie', 'province' => 'Kratie'],
    ['city' => 'Kampong Thom', 'province' => 'Kampong Thom'],
    ['city' => 'Mondulkiri', 'province' => 'Mondulkiri'],
    ['city' => 'Ratanakiri', 'province' => 'Ratanakiri'],
    ['city' => 'Banlung', 'province' => 'Ratanakiri'],
    ['city' => 'Sen Monorom', 'province' => 'Mondulkiri'],
    ['city' => 'Pursat', 'province' => 'Pursat'],
    ['city' => 'Kampong Chhnang', 'province' => 'Kampong Chhnang'],
    ['city' => 'Preah Vihear', 'province' => 'Preah Vihear'],
    ['city' => 'Stung Treng', 'province' => 'Stung Treng'],
    ['city' => 'Koh Rong', 'province' => 'Preah Sihanouk'],
    ['city' => 'Koh Rong Samloem', 'province' => 'Preah Sihanouk'],
    ['city' => 'Chi Phat', 'province' => 'Koh Kong'],
    ['city' => 'Kirirom', 'province' => 'Kampong Speu'],
    ['city' => 'Banteay Chhmar', 'province' => 'Banteay Meanchey'],
    ['city' => 'Kampong Trach', 'province' => 'Kampot'],
    ['city' => 'Chi Pat', 'province' => 'Koh Kong'],
    ['city' => 'Kampong Thom', 'province' => 'Kampong Thom'],
    ['city' => 'Sisophon', 'province' => 'Banteay Meanchey'],
    ['city' => 'Poipet', 'province' => 'Banteay Meanchey'],
    ['city' => 'Svay Rieng', 'province' => 'Svay Rieng'],
    ['city' => 'Suong', 'province' => 'Tboung Khmum'],
    ['city' => 'Doun Kaev', 'province' => 'Takeo'],
    ['city' => 'Kampong Chhnang', 'province' => 'Kampong Chhnang'],
    ['city' => 'Kampong Trabaek', 'province' => 'Prey Veng'],
    ['city' => 'Tbong Khmum', 'province' => 'Tboung Khmum'],
    ['city' => 'Prey Veng', 'province' => 'Prey Veng'],
    ['city' => 'Takeo', 'province' => 'Takeo'],
    ['city' => 'Banteay Meanchey', 'province' => 'Banteay Meanchey'],
    ['city' => 'Kompong Speu', 'province' => 'Kampong Speu'],
    ['city' => 'Kandal', 'province' => 'Kandal'],
    ['city' => 'Oddar Meanchey', 'province' => 'Oddar Meanchey'],
    ['city' => 'Pailin', 'province' => 'Pailin'],
    ['city' => 'Tbong Khmum', 'province' => 'Tboung Khmum'],
];